### PR TITLE
rework argument passing of initObserver and cocoSuiteRunOptimizer

### PR DESCRIPTION
**Pull request by jakobbossek**
Addresses #40

### CODE REVIEW

**Comment by jakobbossek** [comment]
Started working on #40.
Tell me what you think.

**Comment by jakobbossek** [comment]
Did some more fixes. Runs fine now. Coco postprocessing of multiple algorithms works well, too. Going to finish and merge soon. Really tired now 😴

**Comment by berndbischl** [comment]
Now cracks a noble heart. Goodnight, sweet prince;
And flights of angels sing thee to thy rest.

(no homo)

**Comment by jakobbossek** [comment]
Merging. Travis fails because warnings are treated as errors.

**Pull request merged**
